# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
    config.vm.box = "bento/ubuntu-22.04"
    config.vm.network "private_network", ip: "192.168.10.102"
    config.vm.hostname = "worker-2"

    config.vm.provider "vmware_fusion" do |vb|
        vb.gui = false
        vb.memory = "2048"
        vb.vmx["displayName"] = "worker-2"
        vb.cpus = 2
    end

    # Chạy các lệnh shell
    config.vm.provision "shell" do |s|
        ssh_pub_key = File.readlines("#{Dir.home}/.ssh/k8s/id_rsa.pub").first.strip
        s.inline = <<-SHELL
            # Create ci user
            useradd -s /bin/bash -d /home/ci/ -m -G sudo ci
            echo 'ci ALL=(ALL) NOPASSWD: ALL' >> /etc/sudoers
            mkdir -p /home/ci/.ssh && chown -R ci /home/ci/.ssh
            echo #{ssh_pub_key} >> /home/ci/.ssh/authorized_keys

cat >>/etc/hosts<<EOF
192.168.10.100 controlplane
192.168.10.101 worker-1
192.168.10.102 worker-2
EOF
        SHELL
    end
end